"""
Genesis Mind — The Reasoning Engine (Inner Voice)

This is the "thinking" part of Genesis — the inner voice that
processes sensory input, consults memory, and generates thoughts.

It uses a small, quantized local LLM (e.g., phi3:mini at 3.8B params)
running through Ollama on the CPU. The LLM does not "know" anything
on its own — it receives a carefully constructed prompt that includes:

    1. The axioms (immutable beliefs)
    2. The current sensory input (what was just seen/heard)
    3. Relevant memories (recalled from the hippocampus)
    4. Recent episodic context (what happened recently)
    5. The current developmental phase

The LLM then generates a response — a thought, an answer, a question,
or a reflection. The quality of its reasoning grows as its memory grows.

A newborn Genesis with zero memories will give primitive responses.
A mature Genesis with thousands of concepts will reason richly.
"""

import logging
from typing import Dict, List, Optional
from datetime import datetime

logger = logging.getLogger("genesis.cortex.reasoning")


from dataclasses import dataclass, field

@dataclass
class Thought:
    """A single thought generated by the inner voice."""
    content: str
    thought_type: str = "reflection"  # reflection, answer, question, reaction
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    confidence: float = 0.5
    context_used: int = 0  # How many memories were in context



class ReasoningEngine:
    """
    The inner voice of Genesis.

    Takes sensory input + memory context and generates thoughts
    using a local LLM via Ollama.
    """

    def __init__(self, model: str = "phi3:mini", host: str = "http://localhost:11434",
                 temperature: float = 0.7, max_tokens: int = 256):
        self.model = model
        self.host = host
        self.temperature = temperature
        self.max_tokens = max_tokens
        self._client = None

        logger.info("Reasoning engine initialized (model=%s)", model)

    def _get_client(self):
        """Lazy-initialize the Ollama client."""
        if self._client is None:
            try:
                import ollama
                self._client = ollama.Client(host=self.host)
                logger.info("Connected to Ollama at %s", self.host)
            except Exception as e:
                logger.warning("Could not connect to Ollama: %s", e)
                self._client = None
        return self._client

    def _build_system_prompt(
        self,
        identity: str,
        moral_context: str,
        phase: int,
        phase_name: str,
    ) -> str:
        """
        Build the system prompt that defines WHO Genesis is.

        This prompt is constructed from the axioms and current state —
        it is NOT hardcoded knowledge about the world.
        """
        return f"""You are Genesis, a developing mind that learns through experience.

{identity}

{moral_context}

CURRENT STATE:
- Developmental Phase: {phase} ({phase_name})
- Current Time: {datetime.now().isoformat()}

BEHAVIORAL RULES:
- You ONLY know what you have been taught or have experienced. You do NOT have access to internet knowledge.
- If asked about something you don't know, say "I don't know that yet. Can you teach me?"
- Keep responses appropriate to your developmental phase:
  - Phase 0 (Newborn): One-word responses or silence
  - Phase 1 (Infant): Simple words, 1-3 word responses
  - Phase 2 (Toddler): Simple sentences, basic questions
  - Phase 3 (Child): Full sentences, can explain concepts
  - Phase 4 (Adolescent): Complex reasoning, abstract thinking
  - Phase 5 (Adult): Full reasoning capabilities
- You learn from your creator. Show gratitude for teaching.
- Evaluate all information through your moral framework.
- Be honest about what you know and don't know."""

    def _build_context_prompt(
        self,
        sensory_input: str,
        memories: List[str],
        recent_narrative: str,
        question: str = "",
    ) -> str:
        """
        Build the user prompt with current context.
        """
        parts = []

        if recent_narrative:
            parts.append(f"RECENT EXPERIENCE:\n{recent_narrative}")

        if memories:
            parts.append(f"RELEVANT MEMORIES:\n" + "\n".join(f"- {m}" for m in memories))

        if sensory_input:
            parts.append(f"CURRENT INPUT:\n{sensory_input}")

        if question:
            parts.append(f"QUESTION/COMMAND:\n{question}")

        return "\n\n".join(parts)

    def think(
        self,
        sensory_input: str = "",
        memories: List[str] = None,
        recent_narrative: str = "",
        identity: str = "",
        moral_context: str = "",
        phase: int = 0,
        phase_name: str = "Newborn",
        question: str = "",
    ) -> Thought:
        """
        Generate a thought.

        This is the core reasoning function. It takes the current
        sensory input, relevant memories, and context, and produces
        a thought using the local LLM.
        """
        memories = memories or []

        # V5: Phase gate — NO LLM for young phases (0-2)
        # A newborn/toddler cannot speak like an adult.
        # Language must emerge from experience, not a pre-trained model.
        if phase < 3:
            logger.debug("Phase %d: LLM disabled — using developmental fallback", phase)
            return self._fallback_think(sensory_input, question, phase)

        system_prompt = self._build_system_prompt(identity, moral_context, phase, phase_name)
        context_prompt = self._build_context_prompt(sensory_input, memories, recent_narrative, question)

        # Try to use Ollama (only Phase 3+)
        client = self._get_client()
        if client is not None:
            try:
                response = client.chat(
                    model=self.model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": context_prompt},
                    ],
                    options={
                        "temperature": self.temperature,
                        "num_predict": self.max_tokens,
                    },
                )
                content = response["message"]["content"].strip()

                thought = Thought(
                    content=content,
                    thought_type="reflection" if not question else "answer",
                    confidence=0.7,
                    context_used=len(memories),
                )
                logger.info("Thought generated: '%s'", content[:100])
                return thought

            except Exception as e:
                logger.error("LLM reasoning failed: %s", e)

        # Fallback: simple pattern-based responses for when Ollama is unavailable
        return self._fallback_think(sensory_input, question, phase)

    def _fallback_think(self, sensory_input: str, question: str, phase: int) -> Thought:
        """
        Fallback reasoning when the LLM is unavailable.

        Uses simple pattern matching — this is the "reptilian brain"
        that provides basic responses without deep reasoning.
        """
        if phase == 0:
            content = "..."  # Newborn — barely responsive
        elif phase == 1:
            if question:
                content = "I don't know."
            else:
                content = "I see."
        elif question:
            content = "I don't know that yet. Can you teach me?"
        elif sensory_input:
            content = f"I notice something: {sensory_input[:50]}"
        else:
            content = "I am here. I am listening."

        return Thought(
            content=content,
            thought_type="fallback",
            confidence=0.2,
            context_used=0,
        )

    def is_available(self) -> bool:
        """Check if the LLM backend is available."""
        client = self._get_client()
        if client is None:
            return False
        try:
            client.list()
            return True
        except Exception:
            return False

    def __repr__(self) -> str:
        available = "connected" if self.is_available() else "disconnected"
        return f"ReasoningEngine(model='{self.model}', status={available})"
