"""
Genesis Mind — Neural Reasoning Engine (From-Scratch)

V8: Replaces Phi3:mini/Ollama (3.8B pretrained LLM) with a from-scratch
attention-based reasoning network.

Architecture:
    Multi-head self-attention over the concatenated state vector:
    [visual_embedding(64) + auditory_embedding(64) + context(32) + memory_query(64)]
    → 2-layer attention → 64-dim output → ResponseDecoder

This is NOT language generation. It is pattern-matching over learned
associations. The 64-dim output is decoded by the same ResponseDecoder
that maps GRU states to known concepts.

Think of it as a cortical association area — it finds relationships
between current sensory input and stored memories.

Total params: ~30K (vs Phi3's 3.8B). All learned from scratch.
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

logger = logging.getLogger("genesis.cortex.reasoning")


@dataclass
class Thought:
    """A single thought generated by the neural reasoner."""
    content: str                   # Decoded neural output (concept words or babble)
    raw_embedding: np.ndarray = None  # Raw 64-dim thought vector
    thought_type: str = "reflection"
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    confidence: float = 0.5
    context_used: int = 0


class ReasoningNetwork(nn.Module):
    """
    Multi-head self-attention network for associative reasoning.
    
    Takes concatenated sensory + memory vectors, applies attention
    to find patterns, and outputs a 64-dim "thought vector" that
    represents what Genesis thinks about the current input.
    """
    
    def __init__(self, input_dim: int = 224, hidden_dim: int = 64, 
                 num_heads: int = 4, num_layers: int = 2):
        super().__init__()
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        
        # Project input to hidden dim
        self.input_proj = nn.Linear(input_dim, hidden_dim)
        
        # Multi-head self-attention layers
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=hidden_dim,
            nhead=num_heads,
            dim_feedforward=hidden_dim * 2,
            dropout=0.1,
            batch_first=True,
        )
        self.attention = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        
        # Output projection → 64-dim thought vector
        self.output_proj = nn.Linear(hidden_dim, 64)
        
        # Confidence head — how sure is Genesis about this thought?
        self.confidence_head = nn.Linear(hidden_dim, 1)
    
    def forward(self, x: torch.Tensor) -> tuple:
        """
        Args:
            x: (batch, seq_len, input_dim) — sequence of sensory/memory vectors
        Returns:
            thought: (batch, 64) — thought vector
            confidence: (batch, 1) — how sure Genesis is
        """
        # Project to hidden dim
        projected = F.relu(self.input_proj(x))
        
        # Self-attention
        attended = self.attention(projected)
        
        # Pool across sequence (mean pooling)
        pooled = attended.mean(dim=1)
        
        # Output
        thought = self.output_proj(pooled)
        confidence = torch.sigmoid(self.confidence_head(pooled))
        
        return thought, confidence


class ReasoningEngine:
    """
    The neural reasoning system of Genesis — thinks from scratch.
    
    Unlike the old LLM-based reasoner that called Phi3:mini for every
    thought, this uses a small attention network that learns to associate
    sensory inputs with memories. It doesn't "speak English" — it
    produces 64-dim thought vectors that are decoded by the ResponseDecoder.
    
    The quality of reasoning improves as:
    1. More sensory experiences are processed (more training data)
    2. More concepts are learned (richer vocabulary for the decoder)
    3. More associations are formed (better attention patterns)
    """
    
    def __init__(self, input_dim: int = 224, hidden_dim: int = 64,
                 learning_rate: float = 1e-3,
                 storage_path: Optional[Path] = None):
        self.input_dim = input_dim
        self._storage_path = storage_path
        
        self.network = ReasoningNetwork(
            input_dim=input_dim,
            hidden_dim=hidden_dim,
        )
        self.optimizer = torch.optim.Adam(
            self.network.parameters(), lr=learning_rate
        )
        
        self._thought_count = 0
        self._train_steps = 0
        
        self._load()
        
        total_params = sum(p.numel() for p in self.network.parameters())
        logger.info(
            "Neural reasoning engine initialized (params=%d, thoughts=%d)",
            total_params, self._thought_count,
        )
    
    def think(self, visual_embedding: np.ndarray = None,
              auditory_embedding: np.ndarray = None,
              context_vector: np.ndarray = None,
              memory_embeddings: List[np.ndarray] = None,
              phase: int = 0,
              **kwargs) -> Thought:
        """
        Generate a thought from current sensory state.
        
        Builds a sequence of vectors from sensory inputs and memories,
        runs them through the attention network, and returns a thought
        vector that can be decoded by the ResponseDecoder.
        
        Args:
            visual_embedding: 64-dim from VisualCortex
            auditory_embedding: 64-dim from AuditoryCortex  
            context_vector: 32-dim from Proprioception
            memory_embeddings: List of 64-dim stored memory vectors
            phase: Current developmental phase
            
        Returns:
            Thought with raw_embedding and decoded content
        """
        # Build the input sequence
        sequence = self._build_sequence(
            visual_embedding, auditory_embedding,
            context_vector, memory_embeddings,
        )
        
        self.network.eval()
        with torch.no_grad():
            thought_vec, confidence = self.network(sequence)
        
        thought_np = thought_vec.squeeze(0).cpu().numpy()
        conf = confidence.item()
        
        self._thought_count += 1
        
        return Thought(
            content="",  # Will be filled by ResponseDecoder in the caller
            raw_embedding=thought_np,
            thought_type="reflection",
            confidence=conf,
            context_used=len(memory_embeddings) if memory_embeddings else 0,
        )
    
    def train_on_feedback(self, visual_embedding: np.ndarray,
                          auditory_embedding: np.ndarray,
                          context_vector: np.ndarray,
                          target_embedding: np.ndarray) -> float:
        """
        Train the reasoner to produce thoughts closer to a target.
        
        When Genesis receives feedback (reinforcement signal), this
        adjusts the attention weights to produce similar thought
        patterns for similar inputs.
        """
        sequence = self._build_sequence(
            visual_embedding, auditory_embedding,
            context_vector, None,
        )
        target = torch.tensor(target_embedding, dtype=torch.float32).unsqueeze(0)
        
        if target.shape[1] != 64:
            target = target[:, :64] if target.shape[1] > 64 else torch.cat(
                [target, torch.zeros(1, 64 - target.shape[1])], dim=1
            )
        
        self.network.train()
        thought_vec, _ = self.network(sequence)
        
        loss = 1.0 - F.cosine_similarity(thought_vec, target, dim=1).mean()
        
        self.optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(self.network.parameters(), max_norm=1.0)
        self.optimizer.step()
        
        self._train_steps += 1
        if self._train_steps % 50 == 0:
            self._save()
        
        return loss.item()
    
    def _build_sequence(self, visual: np.ndarray = None,
                        auditory: np.ndarray = None,
                        context: np.ndarray = None,
                        memories: List[np.ndarray] = None) -> torch.Tensor:
        """
        Build the input sequence for the attention network.
        
        Each element in the sequence is zero-padded to input_dim.
        The sequence includes: [visual, auditory, context, mem1, mem2, ...]
        """
        vectors = []
        
        def pad_to_dim(v: np.ndarray) -> np.ndarray:
            v = np.array(v, dtype=np.float32).flatten()
            if len(v) >= self.input_dim:
                return v[:self.input_dim]
            return np.pad(v, (0, self.input_dim - len(v)))
        
        if visual is not None:
            vectors.append(pad_to_dim(visual))
        else:
            vectors.append(np.zeros(self.input_dim, dtype=np.float32))
        
        if auditory is not None:
            vectors.append(pad_to_dim(auditory))
        else:
            vectors.append(np.zeros(self.input_dim, dtype=np.float32))
        
        if context is not None:
            vectors.append(pad_to_dim(context))
        else:
            vectors.append(np.zeros(self.input_dim, dtype=np.float32))
        
        # Add memory vectors (up to 8)
        if memories:
            for mem in memories[:8]:
                vectors.append(pad_to_dim(mem))
        
        # Ensure at least 3 sequence elements
        while len(vectors) < 3:
            vectors.append(np.zeros(self.input_dim, dtype=np.float32))
        
        # Stack into (1, seq_len, input_dim)
        arr = np.stack(vectors)
        return torch.tensor(arr, dtype=torch.float32).unsqueeze(0)
    
    def is_available(self) -> bool:
        """Neural reasoner is always available — no external deps."""
        return True
    
    def get_stats(self) -> dict:
        return {
            "thought_count": self._thought_count,
            "train_steps": self._train_steps,
            "total_params": sum(p.numel() for p in self.network.parameters()),
        }
    
    def _save(self):
        if self._storage_path is None:
            return
        self._storage_path.parent.mkdir(parents=True, exist_ok=True)
        torch.save({
            "network": self.network.state_dict(),
            "optimizer": self.optimizer.state_dict(),
            "thought_count": self._thought_count,
            "train_steps": self._train_steps,
        }, self._storage_path)
    
    def _load(self):
        if self._storage_path is None or not self._storage_path.exists():
            return
        try:
            checkpoint = torch.load(self._storage_path, map_location="cpu", weights_only=False)
            self.network.load_state_dict(checkpoint["network"])
            self.optimizer.load_state_dict(checkpoint["optimizer"])
            self._thought_count = checkpoint.get("thought_count", 0)
            self._train_steps = checkpoint.get("train_steps", 0)
            logger.info("Reasoner loaded (%d thoughts, %d train steps)",
                        self._thought_count, self._train_steps)
        except Exception as e:
            logger.error("Failed to load reasoner: %s", e)
    
    def save(self):
        self._save()
    
    def __repr__(self) -> str:
        return f"ReasoningEngine(neural, thoughts={self._thought_count})"
